### ISSUE TITLE
Plugins HTTP Error 409: Conflict

### ISSUE THREAD

**Issue by AdamiHamza** [wunzeco/ansible-kong#16]
## Summary

Error on `ansible-kong/tasks/plugin_add.yml:7`

"matched_plugin_id": "", Can't update plugin when already exists.

```
- name: 0.0.1-initial.yml | Provision KONG
  hosts: localhost
  connection: local
  become: yes

  vars:
    kong_version: 0.13.1
    kong_use_old_config_format: false

  roles:
    #****************#
    #    SERVICES    #
    #****************#
    # --------------- Profile User Statistics --------------- #
    - role: ansible-kong
      kong_task: service
      kong_service_config:
        service:
          name: profile-users-stats
          url: 'http://api.namspace.svc.cluster.local/api/v1/stats'
        routes:
          - paths: [ '/api/v1/stats', '/stats' ]
            methods: [ 'GET', 'OPTIONS' ]
            preserve_host: true
            strip_path: true

    - role: ansible-kong
      kong_task: plugin
      kong_plugin_config:
        name: cors
        service: profile-users-stats
        config:
          origins: '*'
          methods: 'GET'
          credentials: false
          preflight_continue: false
```

## Steps To Reproduce

If we run the playbook for the first time, services, routes and plugins will be created but the second execution it raises  HTTP Error 409: Conflict when adding the plugin.

## Additional Details & Logs

```
TASK [ansible-kong : Get matched plugin id] ****************************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin.yml:54
ok: [localhost] => {
    "ansible_facts": {
        "matched_plugin_id": ""
    },
    "changed": false,
    "failed": false
}
TASK [ansible-kong : debug] ********************************************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin.yml:58
ok: [localhost] => {
    "msg": "Plugin - cors"
}

TASK [ansible-kong : set_fact] *****************************************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin.yml:60
ok: [localhost] => {
    "ansible_facts": {
        "_cmd": "add"
    },
    "changed": false,
    "failed": false
}

TASK [ansible-kong : set_fact] *****************************************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin.yml:62
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}

TASK [ansible-kong : Kong Plugin Object Config] ************************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin.yml:65
included: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin_add.yml for localhost

TASK [ansible-kong : Initialise plugin_exists variable] ****************************************************************************************************************************************************
task path: /root/fugoki-ansible/roles/external/ansible-kong/tasks/plugin_add.yml:3
ok: [localhost] => {
    "ansible_facts": {
        "plugin_exists": false
    },
    "changed": false,
    "failed": false
}
```

```
The full traceback is:
  File "/tmp/ansible_MeVxIb/ansible_module_uri.py", line 468, in main
    uresp['location'] = absolute_location(url, uresp['location'])

fatal: [localhost]: FAILED! => {
    "access_control_allow_origin": "*",
    "changed": false,
    "connection": "close",
    "content": "{\"name\":\"already exists with value 'cors'\"}\n",
    "content_type": "application/json; charset=utf-8",
    "date": "Fri, 25 May 2018 16:37:49 GMT",
    "failed": true,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": {
                "config": {
                    "credentials": false,
                    "methods": "GET",
                    "origins": "*",
                    "preflight_continue": false
                },
                "name": "cors",
                "service_id": "24654971-dbe8-4749-89f0-d7270c18d294"
            },
            "body_format": "json",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Content-Type": "application/json"
            },
            "http_agent": "ansible-httpget",
            "method": "POST",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "201"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "http://kong:8001/plugins/",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "json": {
        "name": "already exists with value 'cors'"
    },
    "msg": "Status code was not [201]: HTTP Error 409: Conflict",
    "redirected": false,
    "server": "kong/0.13.1",
    "status": 409,
    "url": "http://kong:8001/plugins/",
    "via": "1.1 packer-5a802b6f-987a-8190-ee48-0de9ff88de6b (squid/3.5.12)",
    "x_cache": "MISS from packer-5a802b6f-987a-8190-ee48-0de9ff88de6b",
    "x_cache_lookup": "MISS from packer-5a802b6f-987a-8190-ee48-0de9ff88de6b:3128"
}
```

## Expected behaviour
- GET the plugin.
- If exists and plugin parameters changed, PATCH it.
- if exists and plugin parameters unchanged, don't try to recreated the plugin to avoid HTTP Error 409: Conflict.
- if not exists, add it.
