### ISSUE TITLE
Cant register plugins

### ISSUE THREAD

**Issue by vovel** [wunzeco/ansible-kong#20]
Ansible 2.2.3
wunzeco/ansible-kong 1.10

When this block executes:

```
- name: register logging plugin for logstash
  include_role:
    name: wunzeco.kong
    kong_task: plugin
    kong_plugin_config:
      name: tcp-log
      service: prod-k8s
      config: { host: "logstash-aggregator-elb.prod.airmap.com", port: "8888", timeout: "10000", keepalive: "60000" }
  vars:
    kong_use_old_config_format: false
    kong_admin_api_url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8001"
  run_once: true
```

for some unexplainable reason `kong_task` has no value and therefore gets populated with the default, `server`, and then installation of kong is attempted (which is not what i want at all.

I have other task blocks which register services and routes and they work fine. the plugin `kong_task` seems to just get ignored.

Is there something weird about `include_role` and Ansible 2.2.3 or am I missing something obvious about the task block?
