### ISSUE TITLE
Unable to reliably create consumer if more than 100 consumers in kong

### ISSUE THREAD

**Issue by ADeane6** [wunzeco/ansible-kong#28]
In the event that there are more than 100 consumers, kong paginates the consumer list, this can lead the consumer add task to incorrectly count a consumer as not existing as the consumer may not be on the first page. This causes the task to try to create a consumer and fails.

```
# Get list of consumer objects
- name: Get list of kong consumer objects
  uri:
    url: "{{ kong_admin_api_url }}/consumers"
  register: consumers
```
